name: Run-ESLint

on:
  push:
    branches:
      - chakra

jobs:
  Run-ESLint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Install Dependencies
        run: yarn install
      
      - name: Run ESLint
        run: yarn lint
